### role = user
POST http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "username": "yan",
  "password": "qwerwety1"
}

###

PUT http://127.0.0.1:10001/auth/
Content-Type: application/json

{
"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjc3NDkwOTAyfQ.Bj-ZgLB8K9xkKRrucySQuIXjOzp4EOlQWY-tlTqV9JY"
}

### role = admin

POST http://127.0.0.1:10001/auth/
Content-Type: application/json

{
  "username": "hohoho",
  "password": "happynew"
}