"""add new user.favorite_genre

Revision ID: 54234697321e
Revises: dcc1c47f16eb
Create Date: 2022-10-29 11:51:49.563881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54234697321e'
down_revision = 'dcc1c47f16eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genre', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genre', ['favorite_genre'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_genre')

    # ### end Alembic commands ###
