"""add new user.favorite_genre

Revision ID: 641cf5a30b1c
Revises: eeb856535f49
Create Date: 2022-10-29 11:55:27.706765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641cf5a30b1c'
down_revision = 'eeb856535f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genre', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genre', ['favorite_genre'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_genre')

    # ### end Alembic commands ###
