"""remove user.genre_id

Revision ID: cfcb47b8f35f
Revises: 641cf5a30b1c
Create Date: 2022-10-29 12:34:38.587041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcb47b8f35f'
down_revision = '641cf5a30b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
