"""delete user.favorite_genre

Revision ID: f67fb525ace1
Revises: c23b1847ce68
Create Date: 2022-10-29 11:10:30.519265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67fb525ace1'
down_revision = 'c23b1847ce68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genre', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
